//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.8.0.0 (Newtonsoft.Json v9.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace BlazorCssIsolation
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.8.0.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial record Anonymous
    {

        [System.Text.Json.Serialization.JsonPropertyName("blue")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Blue { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("blue-1")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Blue1 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("blue-10")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Blue10 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("blue-2")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Blue2 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("blue-3")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Blue3 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("blue-4")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Blue4 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("blue-5")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Blue5 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("blue-6")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Blue6 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("blue-7")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Blue7 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("blue-8")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Blue8 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("blue-9")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Blue9 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("borderRadius")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double BorderRadius { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("borderRadiusLG")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double BorderRadiusLG { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("borderRadiusOuter")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double BorderRadiusOuter { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("borderRadiusSM")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double BorderRadiusSM { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("borderRadiusXS")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double BorderRadiusXS { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("boxShadow")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string BoxShadow { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("boxShadowCard")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string BoxShadowCard { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("boxShadowDrawerDown")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string BoxShadowDrawerDown { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("boxShadowDrawerLeft")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string BoxShadowDrawerLeft { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("boxShadowDrawerRight")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string BoxShadowDrawerRight { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("boxShadowDrawerUp")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string BoxShadowDrawerUp { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("boxShadowPopoverArrow")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string BoxShadowPopoverArrow { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("boxShadowSecondary")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string BoxShadowSecondary { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("boxShadowTabsOverflowBottom")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string BoxShadowTabsOverflowBottom { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("boxShadowTabsOverflowLeft")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string BoxShadowTabsOverflowLeft { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("boxShadowTabsOverflowRight")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string BoxShadowTabsOverflowRight { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("boxShadowTabsOverflowTop")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string BoxShadowTabsOverflowTop { get; set; }

        /// <summary>
        /// Base component background color. Will derivative container background color with this
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("colorBgBase")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorBgBase { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorBgContainer")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorBgContainer { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorBgContainerDisabled")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorBgContainerDisabled { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorBgElevated")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorBgElevated { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorBgLayout")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorBgLayout { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorBgMask")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorBgMask { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorBgSpotlight")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorBgSpotlight { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorBgTextActive")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorBgTextActive { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorBgTextHover")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorBgTextHover { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorBorder")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorBorder { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorBorderBg")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorBorderBg { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorBorderSecondary")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorBorderSecondary { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorError")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorError { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorErrorActive")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorErrorActive { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorErrorBg")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorErrorBg { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorErrorBgHover")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorErrorBgHover { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorErrorBorder")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorErrorBorder { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorErrorBorderHover")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorErrorBorderHover { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorErrorHover")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorErrorHover { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorErrorOutline")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorErrorOutline { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorErrorText")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorErrorText { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorErrorTextActive")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorErrorTextActive { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorErrorTextHover")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorErrorTextHover { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorFill")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorFill { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorFillAlter")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorFillAlter { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorFillContent")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorFillContent { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorFillContentHover")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorFillContentHover { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorFillQuaternary")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorFillQuaternary { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorFillSecondary")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorFillSecondary { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorFillTertiary")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorFillTertiary { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorHighlight")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorHighlight { get; set; }

        /// <summary>
        /// Weak action. Such as `allowClear` or Alert close button
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("colorIcon")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorIcon { get; set; }

        /// <summary>
        /// Weak action hover color. Such as `allowClear` or Alert close button
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("colorIconHover")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorIconHover { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorInfo")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorInfo { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorInfoActive")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorInfoActive { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorInfoBg")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorInfoBg { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorInfoBgHover")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorInfoBgHover { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorInfoBorder")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorInfoBorder { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorInfoBorderHover")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorInfoBorderHover { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorInfoHover")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorInfoHover { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorInfoText")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorInfoText { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorInfoTextActive")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorInfoTextActive { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorInfoTextHover")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorInfoTextHover { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorLink")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorLink { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorLinkActive")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorLinkActive { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorLinkHover")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorLinkHover { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorPrimary")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorPrimary { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorPrimaryActive")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorPrimaryActive { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorPrimaryBg")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorPrimaryBg { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorPrimaryBgHover")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorPrimaryBgHover { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorPrimaryBorder")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorPrimaryBorder { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorPrimaryBorderHover")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorPrimaryBorderHover { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorPrimaryHover")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorPrimaryHover { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorPrimaryText")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorPrimaryText { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorPrimaryTextActive")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorPrimaryTextActive { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorPrimaryTextHover")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorPrimaryTextHover { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorSplit")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorSplit { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorSuccess")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorSuccess { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorSuccessActive")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorSuccessActive { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorSuccessBg")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorSuccessBg { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorSuccessBgHover")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorSuccessBgHover { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorSuccessBorder")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorSuccessBorder { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorSuccessBorderHover")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorSuccessBorderHover { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorSuccessHover")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorSuccessHover { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorSuccessText")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorSuccessText { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorSuccessTextActive")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorSuccessTextActive { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorSuccessTextHover")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorSuccessTextHover { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorText")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorText { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorTextBase")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorTextBase { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorTextDescription")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorTextDescription { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorTextDisabled")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorTextDisabled { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorTextHeading")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorTextHeading { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorTextLabel")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorTextLabel { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorTextLightSolid")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorTextLightSolid { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorTextPlaceholder")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorTextPlaceholder { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorTextQuaternary")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorTextQuaternary { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorTextSecondary")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorTextSecondary { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorTextTertiary")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorTextTertiary { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorWarning")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorWarning { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorWarningActive")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorWarningActive { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorWarningBg")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorWarningBg { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorWarningBgHover")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorWarningBgHover { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorWarningBorder")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorWarningBorder { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorWarningBorderHover")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorWarningBorderHover { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorWarningHover")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorWarningHover { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorWarningOutline")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorWarningOutline { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorWarningText")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorWarningText { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorWarningTextActive")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorWarningTextActive { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorWarningTextHover")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorWarningTextHover { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("colorWhite")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ColorWhite { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("controlHeight")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ControlHeight { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("controlHeightLG")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ControlHeightLG { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("controlHeightSM")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ControlHeightSM { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("controlHeightXS")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ControlHeightXS { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("controlInteractiveSize")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ControlInteractiveSize { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("controlItemBgActive")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ControlItemBgActive { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("controlItemBgActiveDisabled")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ControlItemBgActiveDisabled { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("controlItemBgActiveHover")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ControlItemBgActiveHover { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("controlItemBgHover")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ControlItemBgHover { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("controlOutline")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ControlOutline { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("controlOutlineWidth")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ControlOutlineWidth { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("controlPaddingHorizontal")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ControlPaddingHorizontal { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("controlPaddingHorizontalSM")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ControlPaddingHorizontalSM { get; set; }

        /// <summary>
        /// Used for DefaultButton, Switch which has default outline
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("controlTmpOutline")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string ControlTmpOutline { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("cyan")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Cyan { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("cyan-1")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Cyan1 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("cyan-10")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Cyan10 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("cyan-2")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Cyan2 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("cyan-3")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Cyan3 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("cyan-4")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Cyan4 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("cyan-5")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Cyan5 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("cyan-6")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Cyan6 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("cyan-7")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Cyan7 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("cyan-8")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Cyan8 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("cyan-9")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Cyan9 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("fontFamily")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string FontFamily { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("fontSize")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double FontSize { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("fontSizeHeading1")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double FontSizeHeading1 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("fontSizeHeading2")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double FontSizeHeading2 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("fontSizeHeading3")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double FontSizeHeading3 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("fontSizeHeading4")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double FontSizeHeading4 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("fontSizeHeading5")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double FontSizeHeading5 { get; set; }

        /// <summary>
        /// Operation icon in Select, Cascader, etc. icon fontSize. Normal is same as fontSizeSM
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("fontSizeIcon")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double FontSizeIcon { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("fontSizeLG")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double FontSizeLG { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("fontSizeSM")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double FontSizeSM { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("fontSizeXL")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double FontSizeXL { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("fontSizes")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public System.Collections.Generic.ICollection<double> FontSizes { get; set; } = new System.Collections.ObjectModel.Collection<double>();

        /// <summary>
        /// For heading like h1, h2, h3 or option selected item
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("fontWeightStrong")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double FontWeightStrong { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("geekblue")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Geekblue { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("geekblue-1")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Geekblue1 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("geekblue-10")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Geekblue10 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("geekblue-2")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Geekblue2 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("geekblue-3")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Geekblue3 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("geekblue-4")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Geekblue4 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("geekblue-5")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Geekblue5 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("geekblue-6")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Geekblue6 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("geekblue-7")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Geekblue7 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("geekblue-8")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Geekblue8 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("geekblue-9")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Geekblue9 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("gold")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Gold { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("gold-1")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Gold1 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("gold-10")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Gold10 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("gold-2")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Gold2 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("gold-3")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Gold3 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("gold-4")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Gold4 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("gold-5")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Gold5 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("gold-6")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Gold6 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("gold-7")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Gold7 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("gold-8")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Gold8 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("gold-9")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Gold9 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("green")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Green { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("green-1")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Green1 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("green-10")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Green10 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("green-2")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Green2 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("green-3")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Green3 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("green-4")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Green4 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("green-5")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Green5 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("green-6")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Green6 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("green-7")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Green7 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("green-8")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Green8 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("green-9")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Green9 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("lime")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Lime { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("lime-1")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Lime1 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("lime-10")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Lime10 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("lime-2")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Lime2 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("lime-3")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Lime3 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("lime-4")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Lime4 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("lime-5")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Lime5 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("lime-6")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Lime6 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("lime-7")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Lime7 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("lime-8")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Lime8 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("lime-9")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Lime9 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("lineHeight")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double LineHeight { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("lineHeightHeading1")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double LineHeightHeading1 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("lineHeightHeading2")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double LineHeightHeading2 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("lineHeightHeading3")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double LineHeightHeading3 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("lineHeightHeading4")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double LineHeightHeading4 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("lineHeightHeading5")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double LineHeightHeading5 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("lineHeightLG")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double LineHeightLG { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("lineHeightSM")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double LineHeightSM { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("lineHeights")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public System.Collections.Generic.ICollection<double> LineHeights { get; set; } = new System.Collections.ObjectModel.Collection<double>();


        [System.Text.Json.Serialization.JsonPropertyName("lineType")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string LineType { get; set; }

        /// <summary>
        /// Border width of base components
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("lineWidth")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double LineWidth { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("lineWidthBold")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double LineWidthBold { get; set; }

        /// <summary>
        /// The **`text-decoration`** shorthand CSS property sets the appearance of decorative lines on text. It is a shorthand for `text-decoration-line`, `text-decoration-color`, `text-decoration-style`, and the newer `text-decoration-thickness` property.
        /// <br/>
        /// <br/>**Syntax**: `&lt;'text-decoration-line'&gt; || &lt;'text-decoration-style'&gt; || &lt;'text-decoration-color'&gt; || &lt;'text-decoration-thickness'&gt;`
        /// <br/>
        /// <br/>| Chrome | Firefox | Safari |  Edge  |  IE   | | :----: | :-----: | :----: | :----: | :---: | | **1**  |  **1**  | **1**  | **12** | **3** |
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("linkDecoration")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]   
        public string LinkDecoration { get; set; }

        /// <summary>
        /// The **`text-decoration`** shorthand CSS property sets the appearance of decorative lines on text. It is a shorthand for `text-decoration-line`, `text-decoration-color`, `text-decoration-style`, and the newer `text-decoration-thickness` property.
        /// <br/>
        /// <br/>**Syntax**: `&lt;'text-decoration-line'&gt; || &lt;'text-decoration-style'&gt; || &lt;'text-decoration-color'&gt; || &lt;'text-decoration-thickness'&gt;`
        /// <br/>
        /// <br/>| Chrome | Firefox | Safari |  Edge  |  IE   | | :----: | :-----: | :----: | :----: | :---: | | **1**  |  **1**  | **1**  | **12** | **3** |
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("linkFocusDecoration")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]   
        public string LinkFocusDecoration { get; set; }

        /// <summary>
        /// The **`text-decoration`** shorthand CSS property sets the appearance of decorative lines on text. It is a shorthand for `text-decoration-line`, `text-decoration-color`, `text-decoration-style`, and the newer `text-decoration-thickness` property.
        /// <br/>
        /// <br/>**Syntax**: `&lt;'text-decoration-line'&gt; || &lt;'text-decoration-style'&gt; || &lt;'text-decoration-color'&gt; || &lt;'text-decoration-thickness'&gt;`
        /// <br/>
        /// <br/>| Chrome | Firefox | Safari |  Edge  |  IE   | | :----: | :-----: | :----: | :----: | :---: | | **1**  |  **1**  | **1**  | **12** | **3** |
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("linkHoverDecoration")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]   
        public string LinkHoverDecoration { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("magenta")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Magenta { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("magenta-1")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Magenta1 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("magenta-10")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Magenta10 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("magenta-2")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Magenta2 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("magenta-3")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Magenta3 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("magenta-4")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Magenta4 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("magenta-5")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Magenta5 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("magenta-6")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Magenta6 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("magenta-7")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Magenta7 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("magenta-8")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Magenta8 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("magenta-9")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Magenta9 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("margin")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double Margin { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("marginLG")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double MarginLG { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("marginMD")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double MarginMD { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("marginSM")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double MarginSM { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("marginXL")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double MarginXL { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("marginXS")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double MarginXS { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("marginXXL")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double MarginXXL { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("marginXXS")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double MarginXXS { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("motionBase")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double MotionBase { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("motionDurationFast")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string MotionDurationFast { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("motionDurationMid")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string MotionDurationMid { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("motionDurationSlow")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string MotionDurationSlow { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("motionEaseInBack")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string MotionEaseInBack { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("motionEaseInOut")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string MotionEaseInOut { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("motionEaseInOutCirc")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string MotionEaseInOutCirc { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("motionEaseInQuint")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string MotionEaseInQuint { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("motionEaseOut")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string MotionEaseOut { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("motionEaseOutBack")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string MotionEaseOutBack { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("motionEaseOutCirc")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string MotionEaseOutCirc { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("motionEaseOutQuint")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string MotionEaseOutQuint { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("motionUnit")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double MotionUnit { get; set; }

        /// <summary>
        /// Define default Image opacity. Useful when in dark-like theme
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("opacityImage")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double OpacityImage { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("opacityLoading")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double OpacityLoading { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("orange")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Orange { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("orange-1")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Orange1 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("orange-10")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Orange10 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("orange-2")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Orange2 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("orange-3")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Orange3 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("orange-4")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Orange4 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("orange-5")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Orange5 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("orange-6")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Orange6 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("orange-7")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Orange7 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("orange-8")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Orange8 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("orange-9")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Orange9 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("padding")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double Padding { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("paddingContentHorizontal")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double PaddingContentHorizontal { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("paddingContentHorizontalLG")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double PaddingContentHorizontalLG { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("paddingContentHorizontalSM")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double PaddingContentHorizontalSM { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("paddingContentVertical")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double PaddingContentVertical { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("paddingContentVerticalLG")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double PaddingContentVerticalLG { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("paddingContentVerticalSM")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double PaddingContentVerticalSM { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("paddingLG")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double PaddingLG { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("paddingMD")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double PaddingMD { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("paddingSM")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double PaddingSM { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("paddingXL")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double PaddingXL { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("paddingXS")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double PaddingXS { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("paddingXXS")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double PaddingXXS { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("pink")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Pink { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("pink-1")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Pink1 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("pink-10")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Pink10 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("pink-2")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Pink2 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("pink-3")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Pink3 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("pink-4")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Pink4 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("pink-5")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Pink5 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("pink-6")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Pink6 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("pink-7")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Pink7 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("pink-8")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Pink8 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("pink-9")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Pink9 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("purple")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Purple { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("purple-1")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Purple1 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("purple-10")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Purple10 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("purple-2")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Purple2 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("purple-3")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Purple3 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("purple-4")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Purple4 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("purple-5")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Purple5 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("purple-6")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Purple6 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("purple-7")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Purple7 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("purple-8")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Purple8 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("purple-9")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Purple9 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("red")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Red { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("red-1")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Red1 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("red-10")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Red10 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("red-2")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Red2 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("red-3")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Red3 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("red-4")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Red4 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("red-5")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Red5 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("red-6")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Red6 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("red-7")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Red7 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("red-8")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Red8 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("red-9")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Red9 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("screenLG")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ScreenLG { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("screenLGMax")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ScreenLGMax { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("screenLGMin")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ScreenLGMin { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("screenMD")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ScreenMD { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("screenMDMax")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ScreenMDMax { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("screenMDMin")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ScreenMDMin { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("screenSM")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ScreenSM { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("screenSMMax")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ScreenSMMax { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("screenSMMin")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ScreenSMMin { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("screenXL")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ScreenXL { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("screenXLMax")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ScreenXLMax { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("screenXLMin")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ScreenXLMin { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("screenXS")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ScreenXS { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("screenXSMax")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ScreenXSMax { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("screenXSMin")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ScreenXSMin { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("screenXXL")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ScreenXXL { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("screenXXLMax")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ScreenXXLMax { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("screenXXLMin")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ScreenXXLMin { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("size")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double Size { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("sizeLG")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double SizeLG { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("sizeMD")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double SizeMD { get; set; }

        /// <summary>
        /// Same as size by default, but could be larger in compact mode
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("sizeMS")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double SizeMS { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("sizePopupArrow")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double SizePopupArrow { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("sizeSM")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double SizeSM { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("sizeStep")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double SizeStep { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("sizeUnit")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double SizeUnit { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("sizeXL")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double SizeXL { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("sizeXS")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double SizeXS { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("sizeXXL")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double SizeXXL { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("sizeXXS")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double SizeXXS { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("volcano")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Volcano { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("volcano-1")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Volcano1 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("volcano-10")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Volcano10 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("volcano-2")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Volcano2 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("volcano-3")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Volcano3 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("volcano-4")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Volcano4 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("volcano-5")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Volcano5 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("volcano-6")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Volcano6 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("volcano-7")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Volcano7 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("volcano-8")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Volcano8 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("volcano-9")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Volcano9 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("wireframe")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public bool Wireframe { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("yellow")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Yellow { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("yellow-1")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Yellow1 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("yellow-10")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Yellow10 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("yellow-2")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Yellow2 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("yellow-3")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Yellow3 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("yellow-4")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Yellow4 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("yellow-5")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Yellow5 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("yellow-6")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Yellow6 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("yellow-7")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Yellow7 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("yellow-8")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Yellow8 { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("yellow-9")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public string Yellow9 { get; set; }

        /// <summary>
        /// Base zIndex of component like BackTop, Affix which can be cover by large popup
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("zIndexBase")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ZIndexBase { get; set; }

        /// <summary>
        /// Base popup component zIndex
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("zIndexPopupBase")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]   
        public double ZIndexPopupBase { get; set; }


    }
}